import { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { createClient } from "@/utils/supabase/server";

// Force dynamic rendering since we are fetching data based on slug
export const dynamic = "force-dynamic";

interface PageProps {
    params: {
        slug: string;
        locale: string;
    };
}

async function getGenerationBySlug(slug: string) {
    // Fetch from backend API (which wraps Supabase logic)
    // Or simpler for server component: use Supabase client directly
    const supabase = await createClient();
    const { data, error } = await supabase
        .from("generations")
        .select("*, profiles(username, avatar_url)")
        .eq("slug", slug)
        .single();

    if (error || !data) {
        return null;
    }
    return data;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
    const generation = await getGenerationBySlug(params.slug);

    if (!generation) {
        return {
            title: "Generation Not Found",
        };
    }

    const title = `${generation.prompt.slice(0, 50)}... - AI Generated by 11Flow`;
    const description = `Check out this AI image generated with prompt: "${generation.prompt}" on 11Flow.`;
    const ogImage = generation.result_url;

    return {
        title: title,
        description: description,
        openGraph: {
            title: title,
            description: description,
            images: [
                {
                    url: ogImage,
                    width: 1024,
                    height: 1024,
                    alt: generation.prompt,
                },
            ],
            type: "website",
        },
        twitter: {
            card: "summary_large_image",
            title: title,
            description: description,
            images: [ogImage],
        },
    };
}

export default async function ExploreDetailPage({ params }: PageProps) {
    const generation = await getGenerationBySlug(params.slug);

    if (!generation) {
        notFound();
    }

    const jsonLd = {
        "@context": "https://schema.org",
        "@type": "ImageObject",
        "contentUrl": generation.result_url,
        "creator": {
            "@type": "Person",
            "name": generation.profiles?.username || "Anonymous",
        },
        "description": generation.prompt,
        "name": generation.prompt.slice(0, 100),
        "datePublished": generation.created_at,
    };

    return (
        <div className="container mx-auto px-4 py-8">
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
            />

            <div className="max-w-4xl mx-auto bg-white rounded-xl shadow-sm overflow-hidden border border-gray-100">
                <div className="relative aspect-square w-full bg-gray-100">
                    <Image
                        src={generation.result_url}
                        alt={generation.prompt}
                        fill
                        className="object-contain"
                        priority
                        sizes="(max-width: 768px) 100vw, (max-width: 1200px) 80vw, 1024px"
                        blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=" // Placeholder blur
                        placeholder="blur"
                    />
                </div>

                <div className="p-6">
                    <h1 className="text-xl font-bold text-gray-900 mb-2 break-words">
                        {generation.prompt}
                    </h1>

                    <div className="flex items-center gap-4 mt-6">
                        <div className="flex items-center gap-2">
                            <div className="w-10 h-10 rounded-full bg-gray-200 overflow-hidden relative">
                                {generation.profiles?.avatar_url ? (
                                    <Image
                                        src={generation.profiles.avatar_url}
                                        alt={generation.profiles.username || "User"}
                                        fill
                                        className="object-cover"
                                    />
                                ) : (
                                    <div className="w-full h-full flex items-center justify-center text-gray-500 font-bold">
                                        {(generation.profiles?.username || "U")[0].toUpperCase()}
                                    </div>
                                )}
                            </div>
                            <div>
                                <p className="text-sm font-medium text-gray-900">
                                    {generation.profiles?.username || "Anonymous"}
                                </p>
                                <p className="text-xs text-gray-500">
                                    {new Date(generation.created_at).toLocaleDateString()}
                                </p>
                            </div>
                        </div>
                    </div>

                    <div className="mt-8 pt-6 border-t border-gray-100">
                        <div className="grid grid-cols-2 gap-4 text-sm">
                            <div>
                                <span className="text-gray-500 block mb-1">Model</span>
                                <span className="font-medium">{generation.model || "Unknown"}</span>
                            </div>
                            <div>
                                <span className="text-gray-500 block mb-1">Dimensions</span>
                                <span className="font-medium">
                                    {generation.width && generation.height
                                        ? `${generation.width}x${generation.height}`
                                        : "Custom"}
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
